class HomePage:
    b1 = "button1"
    b2 = 'button2'
    b3 = "idExample"
    link = "Click me using this link text!"
    button = "buttonClass"
    button1 = "button1"
    button2 = "//*[@id='post-909']/div/div[1]/div/div[3]/div/div[1]/div[2]/div[2]/a"
    link1 = "simpleElementsLink"
    icon = "Clickable Icon"
    icon1 = "//*[@id='post-909']/div/div[1]/div/div[3]/div/div[1]/div[5]/div/div[1]"
    name = "et_pb_contact_name_0"
    mail = "et_pb_contact_email_0"
    radio = "et_builder_submit_button"
    key1 = "Hello"
    key2 = "bb@cya.bye"
    radio1 = "//*[@id='post-909']/div/div[1]/div/div[3]/div/div[1]/div[7]/div/div/div/form/input[1]"
    checkbox = "vehicle"
    checkbox2 = "//*[@id='post-909']/div/div[1]/div/div[3]/div/div[1]/div[8]/div/div/div/form/input[2]"
    dropdown = "//*[@id='post-909']/div/div[1]/div/div[3]/div/div[1]/div[9]/div/div/div/select/option[2]"
    tab = "Tab 2"
    button3 = "//*[@id='button1']"
    button4 = "/html/body/div[1]/div/div/div/article/div/div[1]/div/div[4]/div[1]/div/div[2]/div/div/div/form/button"
    button5 = "//*[@id='button1' and text()='Xpath Button 1']"
    button6 = "//*[@id='button1' and text()='Xpath Button 2']"
    highlight = "//*[@id='post-909']/div/div[1]/div/div[5]/div/div[1]/div/div/div/h4/span"
    highlight1 = "//*[@id='post-909']/div/div[1]/div/div[5]/div/div[2]/div/div/div/h4/span"
    highlight2 = "//*[@id='post-909']/div/div[1]/div/div[5]/div/div[3]/div/div/div/h4/span"
    link2 = "Go to login page"
    key3 = "user[email]"
    key4 = "user[password]"
    button7 = "user[remember_me]"
    button8 = "/html/body/main/div/div/article/form/div[4]/input"
    link3 = "Forgot Password?"
    button9 = "commit"

